image:
  repository: barassistant/server
  pullPolicy: IfNotPresent
  tag: v3@sha256:d1e43b5bd2985777657e769ec9427dfe2faa3f0c98421074f06cdaf97c60899d
saltRimImage:
  repository: barassistant/salt-rim
  pullPolicy: IfNotPresent
  tag: v2@sha256:6d1cf5e69abcdda0af3fbd17612059b8a9bcc071e247c8fb72b622589ad0630d
meiliSearchImage:
  repository: getmeili/meilisearch
  pullPolicy: IfNotPresent
  tag: v1.8@sha256:f1665e2e5bf27d8e209b2b9d238ef562c0d949c4acbd58c94ad5c0bf2ecd43e3
nginxImage:
  repository: nginxinc/nginx-unprivileged
  pullPolicy: IfNotPresent
  tag: 1.26@sha256:395450c06a96858b66c3cf64ff8f6e9234e67c906ab33e68a8b6e896eedab7f2

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            APP_URL: "$API_URL"
            LOG_CHANNEL: "stderr"
            MEILISEARCH_KEY: "$MEILI_MASTER_KEY"
            MEILISEARCH_HOST: "http://meilisearch:7700"
            REDIS_HOST: "redis"
            ALLOW_REGISTRATION: "true"
  salt-rim:
    podSpec:
      containers:
        salt-rim:
          imageSelector: saltRimImage
          env:
            API_URL: "$API_URL"
            MEILISEARCH_URL: "$MEILISEARCH_URL"
            BAR_NAME: "$BAR_NAME"
            DESCRIPTION: "$BAR_DESCRIPTION"
            DEFAULT_LOCALE: "en-AU"
  meili-search:
    podSpec:
      containers:
        meili-search:
          imageSelector: meiliSearchImage
          env:
            MEILI_MASTER_KEY: "$MEILI_MASTER_KEY"
            MEILI_ENV: "production"
  nginx:
    podSpec:
      containers:
        nginx:
          imageSelector: nginxImage
service:
  main:
    targetSelector: nginx
    ports:
      main:
        targetSelector: nginx
        targetPort: 3000
        port: 3000
  #unsure nginx or bar-assistant is need in service#
  #bar-assistant:
  #  enabled: true
  #  targetSelector: main
  #  ports:
  #    bar-assistant:
  #      enabled: true
  #      targetSelector: main
  #      port: 3000
  #      targetPort: 3000
  salt-rim:
    enabled: true
    targetSelector: saltRimImage
    port:
      salt-rim:
        enabled: true
        targetSelector: salt-rim
        port: 8080
        targetPorts: 8080
  meili-search:
    enabled: true
    targetSelector: meiliSearchImage
    port:
      meili-search:
        enabled: true
        targetSelector: meili-search
        port: 7700
        targetPort: 7700

persistence:
  bar_data:
    enabled: true
    mountPath: /var/www/cocktails/storage/bar-assistant
  meilisearch_data:
    enabled: true
    mountPath: /meili_data

redis:
  enabled: true
  includeCommon: true
  redisUsername: default

portal:
  open:
    enabled: true
