image:
  repository: barassistant/server
  pullPolicy: IfNotPresent
  tag: v3@sha256:d1e43b5bd2985777657e769ec9427dfe2faa3f0c98421074f06cdaf97c60899d
saltRimImage:
  repository: barassistant/salt-rim
  pullPolicy: IfNotPresent
  tag: v2@sha256:6d1cf5e69abcdda0af3fbd17612059b8a9bcc071e247c8fb72b622589ad0630d
meiliSearchImage:
  repository: getmeili/meilisearch
  pullPolicy: IfNotPresent
  tag: v1.8@sha256:f1665e2e5bf27d8e209b2b9d238ef562c0d949c4acbd58c94ad5c0bf2ecd43e3
nginxImage:
  repository: nginxinc/nginx-unprivileged
  pullPolicy: IfNotPresent
  tag: 1.26@sha256:395450c06a96858b66c3cf64ff8f6e9234e67c906ab33e68a8b6e896eedab7f2
barassistant:
  meili_master_key: masterKey-make-it-long-for-security
  # needs to be replaced
  base_url: http://localhost:3000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            APP_URL: "{{  .Values.barassistant.base_url  }}/bar"
            LOG_CHANNEL: "stderr"
            MEILISEARCH_KEY: "{{ .Values.barassistant.meili_master_key }}"
            # needs to be replaced with proper way to do this
            MEILISEARCH_HOST: "http://meilisearch:7700"
            REDIS_HOST: 
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "rediscreds" }}'
                key: plainhost
            ALLOW_REGISTRATION: "true"
  salt-rim:
    podSpec:
      containers:
        salt-rim:
          imageSelector: saltRimImage
          env:
            API_URL: "{{  .Values.barassistant.base_url  }}/bar"
            MEILISEARCH_URL: "{{  .Values.barassistant.base_url  }}/search"
            BAR_NAME: "BarAssistant"
            DESCRIPTION: "This is my Bar Assistant"
            DEFAULT_LOCALE: "en-US"
  meili-search:
    podSpec:
      containers:
        meili-search:
          imageSelector: meiliSearchImage
          env:
            MEILI_MASTER_KEY: "{{ .Values.barassistant.meili_master_key }}"
            MEILI_ENV: "production"
  nginx:
    podSpec:
      containers:
        nginx:
          imageSelector: nginxImage
service:
  main:
    targetSelector: salt-rim
    ports:
      main:
        targetSelector: salt-rim
        targetPort: 8080
        port: 4000
  bar:
    targetSelector: main
    ports:
      main:
        targetSelector: main
        targetPort: 3000
        port: 3000
  search:
    targetSelector: meili-search
    ports:
      main:
        targetSelector: meili-search
        targetPort: 7700
        port: 7700

persistence:
  bar-data:
    enabled: true
    targetSelector:
      main: 
        main:
          mountPath: /var/www/cocktails/storage/bar-assistant
  meilisearch-data:
    enabled: true
    targetSelector:
      main: 
        meili-search:
          mountPath: /meili_data
  nginx:
    enabled: true
    targetSelector:
      main: 
        nginx:
          mountPath: /etc/nginx/conf.d/default.conf

redis:
  enabled: true
  includeCommon: true
  redisUsername: default

portal:
  open:
    enabled: true
